//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfaceTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InterfaceTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///
        ///
        ///&lt;!DOCTYPE publicwhip
        ///[
        ///&lt;!ENTITY ndash   &quot;&amp;#8211;&quot;&gt;
        ///&lt;!ENTITY mdash   &quot;&amp;#8212;&quot;&gt;
        ///&lt;!ENTITY iexcl   &quot;&amp;#161;&quot;&gt;
        ///&lt;!ENTITY divide  &quot;&amp;#247;&quot;&gt;
        ///&lt;!ENTITY euro    &quot;&amp;#8364;&quot;&gt;
        ///&lt;!ENTITY trade   &quot;&amp;#8482;&quot;&gt;
        ///&lt;!ENTITY bull    &quot;&amp;#8226;&quot;&gt;
        ///&lt;!ENTITY lsquo   &quot;&amp;#8216;&quot;&gt;
        ///&lt;!ENTITY rsquo   &quot;&amp;#8217;&quot;&gt;
        ///&lt;!ENTITY sbquo   &quot;&amp;#8218;&quot;&gt;
        ///&lt;!ENTITY ldquo   &quot;&amp;#8220;&quot;&gt;
        ///&lt;!ENTITY rdquo   &quot;&amp;#8221;&quot;&gt;
        ///&lt;!ENTITY bdquo   &quot;&amp;#8222;&quot;&gt;
        ///&lt;!ENTITY dagger  &quot;&amp;#8224;&quot;&gt;
        ///
        ///&lt;!ENTITY Ouml   &quot;&amp;#214;&quot; &gt;
        ///&lt;!ENTITY szlig  &quot;&amp;#223;&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string regmem2022_02_28 {
            get {
                return ResourceManager.GetString("regmem2022_02_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;root&gt;
        ///    &lt;user&gt;
        ///        &lt;username&gt;A&lt;/username&gt;
        ///        &lt;id&gt;01&lt;/id&gt;
        ///    &lt;/user&gt;
        ///    &lt;user&gt;
        ///        &lt;username&gt;B&lt;/username&gt;
        ///        &lt;id&gt;02&lt;/id&gt;
        ///    &lt;/user&gt;
        ///    &lt;user&gt;
        ///        &lt;username&gt;C&lt;/username&gt;
        ///        &lt;id&gt;05&lt;/id&gt;
        ///    &lt;/user&gt;
        ///    &lt;user&gt;
        ///        &lt;username&gt;d&lt;/username&gt;
        ///        &lt;id&gt;04&lt;/id&gt;
        ///    &lt;/user&gt;
        ///&lt;/root&gt;.
        /// </summary>
        internal static string XMLTest {
            get {
                return ResourceManager.GetString("XMLTest", resourceCulture);
            }
        }
    }
}
